apiVersion: v1
kind: Service
metadata:
  name: nextjs
spec:
  selector:
    app: nextjs
  ports:
  - protocol: TCP
    port: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  labels:
    app: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: nextjs
        image: nextjs
        ports:
        - containerPort: 3000
        startupProbe:
          httpGet:
            path: /version
            port: 3000
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Startup
          timeoutSeconds: 20
          periodSeconds: 20
          failureThreshold: 15
          initialDelaySeconds: 100
        resources:
          requests:
            memory: 700Mi
            cpu: 200m
          limits:
            memory: 4Gi
            cpu: 4000m
